### ISSUE TITLE
Fixes needed to work for IDA

### ISSUE THREAD

**Issue by maxamg** [alphagov/puppet-gds_dns#2]
IDA team have made a few changes to get it working for them, see https://github.com/maxamg/puppet-gds_dns/commit/805a449b941f711670c7b24df304ab79d50e05fc

Spoken to @dcarley , further action tbc.

**Comment by philandstuff** [comment]
Happy to cherry-pick maxamg@805a449 directly.

**Comment by philandstuff** [comment]
done.
